#!/bin/sh /etc/rc.common

START=90
STOP=15
SERVICE_DAEMONIZE=1
 
start() {        
        echo Starting command1 daemon
        service_start /bin/command1 -ftest
}                 
 
stop() {          
        echo Killing command1 daemon
        service_stop /bin/command1 
}
